version: '3.4'

networks:
  open-telemetry:
    name: custom-network
    
services:  
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - open-telemetry

  users-webapi:
    container_name: users-webapi
    image: ${DOCKER_REGISTRY-}opentelemetry.demo.users.webapi
    build:
      context: .
      dockerfile: src/OpenTelemetry.Demo.Users.WebApi/Dockerfile
    ports:
      - "5000:80"
    networks:
      - open-telemetry
    depends_on: 
      - jaeger
    environment:
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831